---
title: "Explanation of business model categories"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Business models

`gluwasp` uses seven categories to define business models of water supply: *gvt_utility*, *delegated_man*, *municial_brd*, *coop*, *corp_utility*, *pub_corp*, and *private_utility*. The purpose of this document is to explain what each of these categories means. Terminology and definitions are taken from source __Bakker2002__.

## Government utility (gvt_utility)
#### Asset ownership: ___Municipal or regional government___ 
#### Asset operation: ___Municipal or regional administration___
The utility is owned and operated by a municipal government, or a group of municipal governments. The municipal government (usually a specific government department) is responsible for operating and maintaining assets, as well as for planning and investing in new assets. Revenues are generated through property tax or user fees, with rates set by the municipal government, often based on recommendations of national regulatory agency. The government utility model predominates in the industrialized countries.

## Delegated management (delegated_man)
#### Asset ownership: ___Municipal or regional government___ 
#### Asset operation: ___Separate delegated enetities___
The utility is owned by the municipal or regional government, but various core parts of the operation are contracted out to separate entities, including private companies. Delegated parts of the operation may include construction, operation, maintainance, and customer service functions. This is done through a combination of service contracts (1-2 yrs), build-own-operate contracts, lease agreements and concessions. (See Mexico City / Buenon Aires).

## Municipal board or commission (municial_brd)
#### Asset ownership: ___Municipal or regional government___
#### Asset operation: ___Commission or board___
The utility is owned by the government, but operated by a separate legal entity, often termed a Public Utility Commission or a Municipal Board. These boards are typically given a ring-fenced budget, and must raise revenues through user fees. The municipal board model is widespread in the United States.

## Cooperative (coop)
#### Asset ownership: ___Users___
####Asset operation: ___Delagated authority___
Utility is owned by the water users with operations run by a delagated authority. More appropriate for rural areas, very few large cities have adopted this model.

## Corporatized utility (corp_utility)
#### Asset ownership: ___Municipal or regional government___
#### Asset operation: ___PLC (permanent concessionaire)___
The utility is a private company with the main shareholder being the municipal or regional government, which places . This set up is may be considered special similar of delegated management in which the utility is essentially a permanent concessionaire. The utility is also subject to corporate law rather than public law. The utility may be for-profit or not-for-profit.

## Publicly owned corporation (pub_corp)
#### Asset ownership: ___Municipal or regional government___
#### Asset operation: ___State owned enterprise___
Also known as: state-owned company, state-owned entity, state enterprise, publicly owned corporation, government business enterprise, crown corporation, government-owned corporation, government-sponsored enterprises, commercial government agency, state-privatised industry public sector undertaking, local 
public enterprise, or parastatal. These enterprises are owned solely by the Government, but have autonomy on day-to-day operations. They also tend to have financial autonomy.

## Private utility (private_utility)
#### Asset ownership: ___Private company___
#### Asset operation: ___Private company___
Asset ownership and operating duties and is transferred to a private company in privatization. The company then operates in a highly regulated environment as a monopoly provider. England and Wales is the only case where this approach has been adopted.


